export const theme = {
    primaryGreen: '#53764c',
    darkGreen: '#1f281b',
    background: '#fffef6',
    shadesBlue: '#cbd6ef',
    shadesYellow: '#f6e4c4',
    shadesGreen: '#cfe5c3',
    primaryGray: '#706f6f',
    backgroundDark: '#706f6f',
    texto: '#fffdf6',
    textoGray: '#616160',
    backgroundBlue: '#3a3745',
    backgroundWhite: '#fffdf6',
    backgroundSepia: '#f6e4c4',
    backgroundSepiaTransparente: '#f6e4c49c',
    borderLines: '#a29371',
    white: '#ffffff',
    mobile: '576px',
    navSize: '60px',
    width1500: '65%',
    textoSize1500: '20px',
    subtitulo1500: '50px',
    tituloDesktop: '75px',
    tituloDesktop1500: '65px',
    tituloBig1500: '100px',
    paddingButton: '5px 20px',
    fontSizeButton: '25px',
    fontSizeP: '20px',
    comminsoonSize: '35px',
    sectionsHeight: '80vh',


    font_montserrat: '\'Montserrat\', sans-serif; font-weight: 400;' ,
    font_regular: '\'Lora\', serif; font-weight: 400;',
    font_italic: '\'Lora\', serif; font-weight: 400; font-style: italic',
    font_regular_important: '\'Lora\', serif!important; font-weight: 400;',
}