export const theme = {
    primaryGreen: '#53764c',
    darkGreen: '#1f281b',
    background: '#fffef6',
    shadesBlue: '#cbd6ef',
    shadesYellow: '#f6e4c4',
    shadesGreen: '#cfe5c3',
    primaryGray: '#706f6f',
    backgroundDark: '#706f6f',
    texto: '#fffdf6',
    textoGray: '#616160',
    backgroundBlue: '#3a3745',
    backgroundWhite: '#fffdf6',
    backgroundSepia: '#f6e4c4',
    white: '#ffffff',
    mobile: '576px',
    navSize: '60px',

    font_montserrat: '\'Montserrat\', sans-serif; font-weight: 400;' ,
    font_regular: '\'Lora\', serif; font-weight: 400;',
    font_italic: '\'Lora\', serif; font-weight: 400; font-style: italic',
}